### PR TITLE
Add a way to list and get details of a node.

### LINKED ISSUE #140: How to list nodes?
Hello!

Thanks for the scala library.
How can I list the nodes of the cluster? There's `KubernetesClient.pods` but no `KubernetesClient.nodes`.

With the java kubernetes client I can call `api.listNode(null, false, null, null, null, 10, null, null, null, false)`, which is really ugly but gets the nodes.

### PR DESCRIPTION
**Pull request by tomiwu**
This PR is resolves  #140 and essentially provides the capability to list nodes within a clause and retrieve their details.

### CODE REVIEW

**Comment by tomiwu** [comment]
Hi, @joan38. I've observed issues with the tests associated with resource deletion. Specifically, pods were lingering in the termination state for an extended duration. To address this, I have reduced the graceful period. I believe this adjustment should be suitable for testing purposes. Please share your thoughts or let me know if this solution aligns with your needs.

**Comment by joan38** [comment]
Thanks @tomiwu for your contribution. That's a welcome addition.
Sounds like we have some failed tests. Is it related to the shorter graceful period?

**Comment by tomiwu** [comment]
I experimented with those tests, and in most instances, the issue was connected to certain pods not getting removed promptly (remaining in a terminating state), causing the tests to time out. This issue wasn't caused by my changes, but I believe I've resolved it. Essentially, before running every test suite now, I ensure that Minikube has been cleaned up.

**Review by joan38 — APPROVED** [review]

**Comment by joan38** [comment]
Perfect, thanks @tomiwu!

**Pull request merged**
