### PR TITLE
Create resource-returning methods

### PR DESCRIPTION
**Pull request by andreisilviudragnea**
Fix for #103

### CODE REVIEW

**Comment by andreisilviudragnea** [comment]
@joan38 Could you take a look at this? It would be helpful for our team to have this feature.

**Comment by joan38** [comment]
Thanks for the PR @andreisilviudragnea . This is a good idea.
However I think the name `createReturningResource` is a bit too verbose but I don't have many better options.
@hamnis @novakov-alexey @sergiy0 @manusa @tomaszym @danicheg would you like to chime in and suggest other names?

I have `createResource` or `createReturning` in mind.

**Review by danicheg — COMMENTED** [review]
@joan38 I just could suggest yet another variant - `createWithResource` :)

**Comment by novakov-alexey-zz** [comment]
I would recommend `createWithResource` as well

**Comment by andreisilviudragnea** [comment]
@joan38 @danicheg I have pushed the suggested changes and some test fixes.

**Pull request merged**
