### PR TITLE
update API version, fix tests

### PR DESCRIPTION
**Pull request by novakov-alexey**
- adjust tests to work with Kubernetes 1.25 version
- change API version from beta to v1 in CronJobs

### CODE REVIEW

**Comment by novakov-alexey** [comment]
@joan38 I have finally found a time to look at the failing tests. There were a couple of issues in tests

**Comment by novakov-alexey** [comment]
@joan38 you approval is needed to run this workflow. I did not know that GH requires such approval at all. Weird.

**Comment by joan38** [comment]
@novakov-alexey sounds like we have conflicts on this one

**Comment by novakov-alexey** [comment]
@joan38 conflict has been solved. 

P.S. I am trying to improve these tests, but I am running out of tricks and ideas to make them work in Github CI. The main issue is that the number of tests is higher than _minikube_ performance can absorb within meaningful amount of time. We need to redesign tests to reuse the same k8s namespace per resource, because currently we create so many namespaces that their creation and termination is slowing down all the tests dramatically, even though they are running concurrently.

**Comment by novakov-alexey** [comment]
tests work in my fork: https://github.com/novakov-alexey/kubernetes-client/actions/runs/3995375168

**Comment by novakov-alexey** [comment]
Ready for merge

**Comment by joan38** [comment]
Incredible @novakov-alexey! Thank you so much

**Pull request merged**
