### PR TITLE
Adds support for k8s lease resources

### LINKED ISSUE #119: Lease support
Implement Kubernetes Leases support:
https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/lease-v1/

### PR DESCRIPTION
**Pull request by BrainHorse**
Closes https://github.com/joan38/kubernetes-client/issues/119

### CODE REVIEW

**Comment by joan38** [comment]
Great work, thanks @BrainHorse

**Comment by BrainHorse** [comment]
Thank you too! 🙇‍♂️ Looking forward to new version with this.

**Comment by joan38** [comment]
Can you try `8.1-2-0d89a0c-SNAPSHOT` and let me know if that looks good?

You need to add the snapshot repo https://oss.sonatype.org/content/repositories/snapshots/

**Comment by BrainHorse** [comment]
Works fine for me! Thanks

**Pull request merged**
