### PR TITLE
Switch build to Mill

### PR DESCRIPTION
**Pull request by joan38**
I've been switching my projects to Mill lately since it's super fast and the DSL is way better.
@novakov-alexey Do you mind having a try and let me know if you have any pain points before I merge this?
Mill is embedded so running `./mill __.compile`, `./mill __.test`... should do what you expect without installing anything.
If you are using Idea you can generate the config with `mill mill.scalalib.GenIdea/idea`. Metals should work too. There is also BSP support but I can't confirm it's 100% working.
More info on http://sca.la/mill

### CODE REVIEW

**Comment by novakov-alexey-zz** [comment]
Sure, let me try it. Looks very interesting.

**Comment by novakov-alexey-zz** [comment]
@joan38 Mill is really faster than SBT. I noticed few small issues:
1. Mill shell wrapper script does not propagate environment variables like `KUBE_CONTEXT_NAME` exported via bash `export` command. However, it does that, once I installed Mill on my machine and run it via `mill` command, i.e. not `./mill`.
2. Parallel test execution. 
Mill GitHub Action command is running tests sequentially? However, SBT run them in parallel. I found in Mill documentation we can run tasks with multiple threads by using `-j <number of threads>`. It works, but Kubernetes tests for different Scala versions are started to run in parallel which is bad, because they clash due to shared namespaces. Basically, it is like to start the same test twice in parallel, most of the times it fails. How to enable parallelism only within the one Scala version? Currently, I am getting such interwoven Mill shell output:

```
kubernetes-client[2.13.2].test.test: - should fail on non existing namespace
kubernetes-client[2.13.2].test.test: - should fail on non existing Pod
kubernetes-client[2.13.2].test.test: list
kubernetes-client[2.13.2].test.test: - should list Pods
kubernetes-client[2.13.2].test.test: list
kubernetes-client[2.13.2].test.test: - should list Pods with a label
kubernetes-client[2.12.11].test.test: - should create a Service
kubernetes-client[2.12.11].test.test: - should update a Service already created
kubernetes-client[2.12.11].test.test: get
kubernetes-client[2.12.11].test.test: - should get a Service
kubernetes-client[2.12.11].test.test: - should fail on non existing namespace
```

**Comment by joan38** [comment]
Good points I will look into enabling parallel test execution.

**Comment by joan38** [comment]
1. Well at least we have an embedded script which we didn't have with SBT. I would say if one wants to export env var it can install Mill.
This is exceeding the status quo with SBT.
2. The parallel execution of tests is not build tool dependent. It's a Scalatest thing and they run in parallel independently if you run them in SBT or Mill.
Tho we can notice that tests are running longer with Mill because it runs them twice for 2.12 and 2.13. If we wanted to run then once for one target only we would have to do `mill __[2.13.2].test` (recursively run `test` everywhere) or `mill _[2.13.2].test` (run the `test` of every top level projects) or `mill kubernetes-client[2.13.2].test`
This is also an improvement over the status quo with SBT.

On a separate note I've tested BSP and it's working fine with non cross compiled projects except that is doesn't import build related deps so build.sc is all red in Intellij. I reported that with https://github.com/lihaoyi/mill/issues/863.

Our project is cross compiled 2.12 and 2.13, and here BSP support is completely messed up. I reported that with https://github.com/lihaoyi/mill/issues/864. That one makes me sad I might try to contribute a fix if I find time.

Thanks

**Comment by joan38** [comment]
Ok I just noticed what's going on for the 2nd point.
We are running tests 2 times with `__.test` in each target because it runs `kubernetes-client[2.12.11].test` taking the default target and then `kubernetes-client[2.12.11].test.test`

**Comment by joan38** [comment]
After discussing on mill's Gitter they actually fixed that in master.

**Comment by novakov-alexey-zz** [comment]
Ok, as I understood mill is still executing scalatests suites in parallel, however overall test execution is longer than it was with SBT? This sounds a bit strange. I am wondering what `-j` option is doing in Mill task execution logic then.

**Comment by joan38** [comment]
The execution is longer because mill is running twice the tests. This is due to a behavior (not really a bug) that is fixed in the upcoming release.
Mill modules can have a default target to run, so for example `mill kubernetes-client` will run `mill kubernetes-client.run` because `JavaModule` which is inherited by `ScalaModule` and `CrossScalaModule` defines [`defaultCommandName`](https://github.com/lihaoyi/mill/blob/ad23e6434836c6d8ccdaae31a6a788b55a4c489c/scalalib/src/JavaModule.scala#L32). Same for `mill kubernetes-client.test` will run `mill kubernetes-client.test.test` because it inherits TestModule that defines [`defaultCommandName`](https://github.com/lihaoyi/mill/blob/ad23e6434836c6d8ccdaae31a6a788b55a4c489c/scalalib/src/JavaModule.scala#L577).

When you run mill __.test it will find both the targets and modules recursively, for modules it gets the defaultCommandName and we end up with duplicates. That's something fixed in the upcoming release.

The `-j` option is executing targets in parallel as much as it can if one has no dependency on the other one. I think SBT is doing this poorly.

**Comment by novakov-alexey-zz** [comment]
Ok, understood, thanks for explanation. Hopefully, new release will run the tests faster.

**Comment by novakov-alexey-zz** [comment]
@joan38 do you plan to merge this PR into master? I would like to implement this feature: #18

**Pull request merged**
