### PR TITLE
custom resources support

### PR DESCRIPTION
**Pull request by novakov-alexey-zz**
Add custom resources API for any user spec and status types

### CODE REVIEW

**Comment by novakov-alexey-zz** [comment]
@joan38 ready for code review.

**Review by joan38 — APPROVED** [review]
Thanks

**Comment by joan38** [comment]
@novakov-alexey @novakov-alexey-zz I had to comment some of the tests [here](https://github.com/joan38/kubernetes-client/commit/fafc6cbfe1f931909d1d3829d1da43e8bfa990af) because it was flaky.
I was unable to make it work. Would you have some time to look at it?

**Comment by novakov-alexey** [comment]
@joan38 sure, I will try to look at them this week.

**Pull request merged**
