### PR TITLE
Upgrade to k8s v1.18

### PR DESCRIPTION
**Pull request by novakov-alexey-zz**
related to issue #7 

- This PR updates **swagger.json** to Kubernetes 1.18.
- Tests have been run on k8s v.14. Everything is fine. So I assume newly generated K8s API classes are going to work with version range [1.14-1.18] 

PR needs to be checked after #6 is merged to master

### CODE REVIEW

**Comment by novakov-alexey-zz** [comment]
@joan38 please check after #6

**Comment by novakov-alexey-zz** [comment]
Rebased on latest master. Change diff must be smaller now.

**Comment by joan38** [comment]
Thanks! Can you rebase again on master and format with `sbt style` (now it runs both scalafmt and scalafix at once). I merged #9

**Comment by novakov-alexey-zz** [comment]
Ready

**Comment by joan38** [comment]
I think you still have some conflicts:
Screen Shot 2020-04-13 at 09 59 07

**Comment by novakov-alexey-zz** [comment]
That is weird. Let me create new PR from master to master branch instead.

**Pull request closed without merging**
